VT-5781 NewEgg Throttling Quantity Sync
skuvault-integrations/newEggAccess pull request #19
Opened 2022-12-20 09:11 UTC by mrassudishkin

Throttler. Looks like we take it from ChannelAdvisor. So our limits don't work with response from NewEgg.
So I removed code for CA - for example timer. It became simpler. Added code for using reset time and limits from response of NewEgg. Added tests.

2022-12-20 10:44 UTC, andrey-kozlov-skuvault commented on src/NewEggTests/Throttling/ImmediateDelayer.cs
> +	public class ImmediateDelayer : IDelayer
Looks like you do not use it - then why add?

2022-12-20 10:44 UTC, andrey-kozlov-skuvault commented on src/NewEggTests/Throttling/ThrottlerTest.cs
> +			await _throttler.ExecuteAsync(() => Task.FromResult(new object()));
Let's follow our common structure:
```csharp
// Arrange

// Act

// Assert
```

2022-12-20 10:44 UTC, andrey-kozlov-skuvault commented on src/NewEggTests/Throttling/ThrottlerTest.cs
> +			await _delayerMock.Received(numberOfRetries).Delay(Arg.Any<TimeSpan>());
Here we can check specific delay value - it should be 30 secs, right?

2022-12-20 11:24 UTC, mrassudishkin commented on src/NewEggAccess/Services/BaseService.cs
> +		private (string RateLimit, string RateRemaining, string RateResetTime) GetRateLimit(IHttpResponseMessage response)
I thought that it's better. Reverted.

2022-12-20 11:24 UTC, mrassudishkin commented on src/NewEggTests/Throttling/ImmediateDelayer.cs
> +	public class ImmediateDelayer : IDelayer
Removed

2022-12-20 11:24 UTC, mrassudishkin commented on src/NewEggTests/Throttling/ThrottlerTest.cs
> +			await _throttler.ExecuteAsync(() => Task.FromResult(new object()));
Done

2022-12-20 11:25 UTC, mrassudishkin commented on src/NewEggTests/Throttling/ThrottlerTest.cs
> +			await _delayerMock.Received(numberOfRetries).Delay(Arg.Any<TimeSpan>());
I would want that I can check it. But time period will be less than 30 sec, because inside method we do DateTime.UtcNow.

2022-12-21 03:39 UTC, slav requested changes

2022-12-21 03:39 UTC, slav commented on src/NewEggAccess/Services/BaseService.cs
> +			NewEggLogger.LogTrace(string.Format("{0}, Total calls: {1}, Remaining calls: {2}, Reset time: {3}", info,
We can't use templates here?

2022-12-21 03:39 UTC, slav commented on src/NewEggAccess/Throttling/Throttler.cs
> +					Trace.WriteLine($"[{ DateTime.Now }] We have quota remains { RateLimit.Remaining }. Continue work" );
Where does this Trace go to?

2022-12-21 08:20 UTC, andrey-kozlov-skuvault commented on src/NewEggTests/Throttling/ThrottlerTest.cs
> +			await _delayerMock.Received(numberOfRetries).Delay(Arg.Any<TimeSpan>());
@mrassudishkin 
For such a cases, we can introduce dependency for getting time instead of static DateTime.UtcNow, just like with `IDelayer`. It is pretty common for DateTime, such an example even could be found in MS unit testing docs.
```csharp
/// <summary>
/// Abstraction for getting DateTime related props:
/// https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#stub-static-references.
/// Used in tests to be able to substitute static DateTime dependency.
/// </summary>
public interface IDateTimeProvider
{
    DateTime UtcNow();
}

public class DateTimeProvider : IDateTimeProvider
{
    public DateTime UtcNow() => DateTime.UtcNow;
}
```

2022-12-22 08:18 UTC, mrassudishkin commented on src/NewEggTests/Throttling/ThrottlerTest.cs
> +			await _delayerMock.Received(numberOfRetries).Delay(Arg.Any<TimeSpan>());
Great idea, thank you, done.

2022-12-22 08:19 UTC, mrassudishkin commented on src/NewEggAccess/Services/BaseService.cs
> +			if (limits == null) return;
Yes, this is correctly here

2022-12-22 08:25 UTC, mrassudishkin commented on src/NewEggAccess/Services/BaseService.cs
> +			NewEggLogger.LogTrace(string.Format("{0}, Total calls: {1}, Remaining calls: {2}, Reset time: {3}", info,
I wouldn't update logging in this ticket. It should be update fully then. Made $"" format here.

2022-12-22 08:26 UTC, mrassudishkin commented on src/NewEggAccess/Throttling/Throttler.cs
> +					Trace.WriteLine($"[{ DateTime.Now }] We have quota remains { RateLimit.Remaining }. Continue work" );
I think nowhere. Updated to NewEggLogger.LogTrace but in any case we have this code in #DEBUG pragma.

2022-12-22 09:42 UTC, andrey-kozlov-skuvault commented on src/NewEggAccess/Throttling/Delayer.cs
> +	}
Maybe it makes sense to move this file to the same place as DateTimeProvider, as this can be used in different places, theoretically, it has not throttling specific.

2022-12-22 09:42 UTC, andrey-kozlov-skuvault commented on src/NewEggTests/Throttling/ThrottlerTest.cs
> +			// we should truncate milliseconds because NewEgg doesn't work with it
Let's make this comment a bit more accurate:
// we should truncate milliseconds because NewEgg returns time as string without milliseconds in the corresponding header

2022-12-22 09:55 UTC, mrassudishkin commented on src/NewEggAccess/Throttling/Delayer.cs
> +	}
Done

2022-12-22 09:56 UTC, mrassudishkin commented on src/NewEggTests/Throttling/ThrottlerTest.cs
> +			// we should truncate milliseconds because NewEgg doesn't work with it
Done

2022-12-22 10:18 UTC, andrey-kozlov-skuvault approved these changes

2022-12-26 09:18 UTC, dk-skuvault approved these changes

2022-12-27 16:09 UTC, slav approved these changes

2023-01-31 10:23 UTC, merged