2021-05-04 GUARD-1846 NewEgg: Business Account Support
skuvault-integrations/newEggAccess pull request #8
Opened 2021-05-04 11:36 UTC by maxim-saltanov-skuvault

BusinessAccount support has been implemented. To reduce the risk of breaking something in existing RegularAccounts, I had to implement separate logic and unit tests for BusinessAccount. A separate service (CredsService) has also been implemented for faster checking of the validity of Credentials for both types of accounts.

2021-05-04 12:50 UTC, nathan-skuvault approved these changes
Looks like this is just carbon copy of existing integration with some changes for Business Accounts. Looked over it and nothing big sticks out to me. Should be ready for testing!

2021-05-04 21:34 UTC, maxim-skuvault commented on src/NewEggAccess/BusinessAccount/Models/Commands/GetFeedStatusCommand.cs
> +	public class GetFeedStatusCommand : NewEggCommand
@maxim-saltanov-skuvault A lot of commands are the same here and in BusinessAccount. Perhaps for those, we can create <command type>CommandBase.cs and then both would inherit from it. This would avoid duplication. We would have flexibility for any future changes to them independently or common changes to the base.

2021-05-04 21:38 UTC, maxim-skuvault commented on src/NewEggAccess/BusinessAccount/Models/Commands/NewEggCommand.cs
> +				return $"{ this.Config.ApiBaseUrl }{ "/b2b" }{ this.RelativeUrl }?{ urlParameters }";
@maxim-saltanov-skuvault , For consistency, can we call `GetPlatformUrl` here as we do in NewEggAccess\Models\Commands\NewEggCommand.cs?

2021-05-04 21:53 UTC, maxim-skuvault commented on src/NewEggAccess/BusinessAccount/Services/BaseService.cs
> +﻿using CuttingEdge.Conditions;
@maxim-saltanov-skuvault , Like with the Models, this appears to be identical to the BaseService.cs in NewEggAccess/Services/. To reduce redundancy, we could move all of this into a common NewEgg BaseService, then I guess have a separate BusinessAccountBaseService.cs and perhaps ConsumerBaseService.cs?

2021-05-04 22:05 UTC, maxim-skuvault requested changes
@maxim-saltanov-skuvault , See specific comments/suggestions, but overall I'm concerned that it will now be unclear what's in /NewEggAccess/Models, /NewEggAccess/Services compared to /NewEggAccess/BusinessAccount/Models, /NewEggAccess/BusinessAccount/Services. At first glance it looks like /NewEggAccess/Models, /NewEggAccess/Services are the common/base classes but they're not really. They're for the consumer newegg.com.

One alternative would be to move the current /NewEggAccess/Models, /NewEggAccess/Services classes to NewEggAccess/Consumer/Models, Services. Anything that's common/base to both consumer and business could go into /NewEggAccess/Models, Services. This would be slightly more work but would reduce duplication and make it clearer. And might help if we add support for CA

2021-05-05 08:46 UTC, maxim-saltanov-skuvault commented on src/NewEggAccess/BusinessAccount/Models/Commands/GetFeedStatusCommand.cs
> +	public class GetFeedStatusCommand : NewEggCommand
@maxim-skuvault When we discussed this task with Jay, it was decided that now there is no need to refactor and I should just repeat the logic for the Business Account, as it is implemented for the Regular Account (so it's mostly duplicated at moment), and do it so as not to affect the current implementation. In the future, we will create a separate ticket and do a general refactoring. I do not see any point in wasting time now on what we in any case then plan to rework for a common implementation for different types of accounts.

2021-05-05 08:50 UTC, maxim-saltanov-skuvault commented
> Looks like this is just carbon copy of existing integration with some changes for Business Accounts. Looked over it and nothing big sticks out to me. Should be ready for testing!

@nathan-skuvault In general, yes, but BusinessAccount does not support some methods (and suggests using others) and the response and request parameters for existing methods are also sometimes different. I tried to take into account all the requirements and unit tests passed, but in general everything will be more clear when I test this access library inside v1.

2021-05-05 11:17 UTC, jnewman-sv commented on src/NewEggAccess/BusinessAccount/Models/Commands/GetFeedStatusCommand.cs
> +	public class GetFeedStatusCommand : NewEggCommand
@maxim-saltanov-skuvault  I was under the impression that we decided not to do a major refactor of the base code, but to use it as the base for Newegg business via inheritance and override values where necessary.  That way we aren't duplicating code and the business classes only need to be changed in the case where they differ.  This way we also keep the benefit of a separate namespace for all business requests.


As an example - this class would simply be:

```suggestion
public class GetFeedStatusCommand : NewEggAccess.Models.Commands.GetFeedStatusCommand
{
	public GetFeedStatusCommand( NewEggConfig config, NewEggCredentials credentials, string payload ) : base( config, credentials, payload )
		{
		}
}
```
I do agree that @maxim-skuvault 's suggestion would be best - as was your initial thought - but as I recall it just sounded like it would take a lot of time to do that now.  I believe the thought was to make a backlog ticket for that refactoring.  If we're to the point where that refactoring would take the same amount of time as simplifying the business account logic via my suggestion - I'm fine with it - but I'll leave that decision up to you.

2021-05-05 12:01 UTC, maxim-saltanov-skuvault commented on src/NewEggAccess/BusinessAccount/Models/Commands/GetFeedStatusCommand.cs
> +	public class GetFeedStatusCommand : NewEggCommand
@maxim-skuvault  / @jnewman-sv I thought that the main goal was not to touch the existing code and not to change the existed classes for regular accounts. But I agree that we can simplify BA implementation and to less the duplications of the existing code - so I will revise the code and simplify where possible (as in your examples). But I think we agree that a big changes / refactoring is not required for now?

2021-05-05 14:09 UTC, maxim-skuvault approved these changes

2021-05-05 14:09 UTC, maxim-skuvault commented on src/NewEggAccess/BusinessAccount/Models/Commands/GetFeedStatusCommand.cs
> +	public class GetFeedStatusCommand : NewEggCommand
@maxim-saltanov-skuvault Sounds good to tackle refactoring in a separate backlog ticket.

2021-05-06 11:20 UTC, jnewman-sv approved these changes

2021-06-29 13:59 UTC, chris-skuvault approved these changes

2021-08-02 16:45 UTC, merged